# Generated by Django 4.1.3 on 2022-11-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
