# Generated by Django 4.1.3 on 2022-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='passwords',
            field=models.ManyToManyField(blank=True, to='core.password'),
        ),
    ]
