# Generated by Django 4.1.3 on 2022-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='passwords',
            field=models.ManyToManyField(blank=True, related_name='organization_passwords', to='core.password'),
        ),
    ]
