# Generated by Django 4.1.3 on 2022-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organization_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='duration_in_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='password',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
