# Generated by Django 4.1.3 on 2022-11-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
